version: '3'

services: 
  db:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes: 
      - ./docker/redis:/usr/local/etc/redis
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
